dist: trusty
sudo: required
language: cpp
compiler: clang

before_script:
- sudo apt-get install -y -qq graphviz doxygen libboost-test1.54-dev
- cmake -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- doxygen Doxyfile
deploy:
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script:
  - curl -T print_ip-1.1.$TRAVIS_BUILD_NUMBER-Linux.deb -ucezarnik:$BINTRAY_API_KEY "https://api.bintray.com/content/cezarnik/homework/print_ip/$TRAVIS_BUILD_NUMBER/print_ip-1.1.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
